# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hello',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
